In [1]:
import pandas as pd
jejudata20=pd.read_excel('C:/Users/user/.jupyter/data20.xlsx')
del jejudata20["데이터기준일자"]
del jejudata20["총 유동인구"]
pd.options.display.float_format = '{:.2f}'.format
jejudata20

              년월   시도명 읍면동명                업종명   이용자수        이용금액
0     2020-01-01  서귀포시  남원읍         건강보조식품 소매업     10     1475000
1     2020-01-01  서귀포시  남원읍            골프장 운영업   3929   727062477
2     2020-01-01  서귀포시  남원읍        과실 및 채소 소매업   3313   159828593
3     2020-01-01  서귀포시  남원읍  관광 민예품 및 선물용품 소매업    366     6843000
4     2020-01-01  서귀포시  남원읍       그외 기타 종합 소매업     12     5210000
...          ...   ...  ...                ...    ...         ...
14030 2020-12-01  서귀포시  중앙동                호텔업     11     2310000
14031 2020-12-01  서귀포시  중앙동      화장품 및 방향제 소매업    782    59603540
14032 2020-12-01  서귀포시  천지동         건강보조식품 소매업     61     8551160
14033 2020-12-01  서귀포시  중앙동            한식 음식점업  25776  1062824272
14034 2020-12-01  서귀포시  천지동        과실 및 채소 소매업   5445   297297345

[14035 rows x 6 columns]

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('산업분류.csv',encoding='cp949')
df = df.drop(columns = ['시도명','시군구명','법정동명','행정동코드','법정동코드','지번주소','도로명주소','신우편번호','경도','위도'])
df=df.sort_values(by=['행정동명'], axis=0)
df

              상호명 상권업종대분류명   상권업종중분류명     상권업종소분류명   표준산업분류명 행정동명
6121       칠성골흑돼지       음식         한식       갈비/삼겹살   한식 음식점업  건입동
7953       골목정육식당       음식         한식       갈비/삼겹살   한식 음식점업  건입동
1565         들물갈비       음식         한식       갈비/삼겹살   한식 음식점업  건입동
16343         봉성장       숙박  모텔/여관/여인숙    모텔/여관/여인숙       여관업  건입동
8040   고집돌우럭제주공항점       음식     일식/수산물  수산물전문음식점-종합   한식 음식점업  건입동
...           ...      ...        ...          ...       ...  ...
17803      페이보리오리       음식         양식     정통양식/경양식  서양식 음식점업  효돈동
16088      일성수산횟집       음식     일식/수산물           횟집   한식 음식점업  효돈동
16482        청마식당       음식         한식    한식/백반/한정식   한식 음식점업  효돈동
10766   쇠소깍복순이네식당       음식         한식    한식/백반/한정식   한식 음식점업  효돈동
3128         새원갈비       음식         한식       갈비/삼겹살   한식 음식점업  효돈동

[18196 rows x 6 columns]

In [4]:
count = pd.DataFrame(df.groupby(['행정동명','상권업종대분류명']).size())
count.reset_index(drop=False, inplace=True)
count.rename(columns={0:'점포 수'}, inplace=True)
count=count.sort_values(by=['행정동명','상권업종대분류명'])
count

    행정동명 상권업종대분류명  점포 수
0    건입동       소매    26
1    건입동       숙박    26
2    건입동       음식   159
3    구좌읍     문화레저     1
4    구좌읍       소매    65
..   ...      ...   ...
131  화북동       숙박     2
132  화북동       음식   229
133  효돈동       소매    30
134  효돈동       숙박     7
135  효돈동       음식    91

[136 rows x 3 columns]

In [6]:
#읍면동별 매장수
food_count=count[count.상권업종대분류명=='음식']
del food_count['행정동명']
del food_count['상권업종대분류명']
food_count=food_count.reset_index(drop=True)

some_count=count[count.상권업종대분류명=='소매']
del some_count['행정동명']
del some_count['상권업종대분류명']
some_count=some_count.reset_index(drop=True)

activity_count=count[count.상권업종대분류명=='문화레저']

sleep_count=count[count.상권업종대분류명=='숙박']
del sleep_count['행정동명']
del sleep_count['상권업종대분류명']
sleep_count=sleep_count.reset_index(drop=True)

In [9]:
#읍면동별 매출액
food=jejudata20[(jejudata20["업종명"]=="한식 음식점업")
    |(jejudata20["업종명"]=="중식 음식점업")
    |(jejudata20["업종명"]=="일식 음식점업")
    |(jejudata20["업종명"]=="서양식 음식점업")
    |(jejudata20["업종명"]=="비알콜 음료점업")
    |(jejudata20["업종명"]=="기타 외국식 음식점")
    |(jejudata20["업종명"]=="피자, 햄버거, 샌드위치 및 유사 음식점업")]

food_group=food.groupby(["읍면동명"],as_index=False).sum()
food_group["업종명"]="음식"
food_group=food_group.join(food_count)
food_group["점포당 매출액"]=food_group["이용금액"]/food_group["점포 수"]


some=jejudata20[(jejudata20['업종명']=="과실 및 채소 소매업")
    |(jejudata20["업종명"]=="관광 민예품 및 선물용품 소매업")
   |(jejudata20["업종명"]=="수산물 소매업")
    |(jejudata20["업종명"]=="육류 소매업")
    |(jejudata20["업종명"]=="빵 및 과자류 소매업")]
            
    
some_group=some.groupby(["읍면동명"],as_index=False).sum()
some_group["업종명"]="소매업"
some_group=some_group.join(some_count)
some_group["점포당 매출액"]=some_group["이용금액"]/some_group["점포 수"]

sleep=jejudata20[(jejudata20["업종명"]=="호텔업")
                |(jejudata20["업종명"]=="휴양콘도")
                |(jejudata20["업종명"]=="여관업")]

sleep_group=sleep.groupby(["읍면동명"],as_index=False).sum()
sleep_group["업종명"]="숙박업"
sleep_group=sleep_group.join(sleep_count)
sleep_group["점포당 매출액"]=sleep_group["이용금액"]/sleep_group["점포 수"]


activity=jejudata20[(jejudata20["업종명"]=="스포츠 및 레크레이션 용품 임대업")
                    |(jejudata20["업종명"]=="기타 수상오락 서비스업")]

activity_group=activity.groupby(["읍면동명"],as_index=False).sum()
activity_group["업종명"]="문화레저"

activity_group[]

In [11]:
#food_group.to_csv("식음매출.csv",index=True)
#sleep_group.to_csv("숙박매출.csv",index=True)
#some_group.to_csv("소매매출.csv",index=True)
#activity_group.to_csv("문화레저매출.csv",index=True)

In [11]:
import pandas as pd
data=pd.read_csv("문화레저매출.csv")
data["1인당이용금액"]=data["이용금액"]/data["이용자수"]
pd.options.display.float_format = '{:.2f}'.format
data=data.sort_values(by=['이용자수'],ascending=False)
data.head().to_csv("문화레저최종.csv")

In [10]:
df_ = pd.concat([some_group,sleep_group,food_group, activity_group])
df_ = df_.sort_values(by=['업종명','읍면동명'])
df_.to_csv("20년도매장수,매출액.csv",index=True)