In [4]:
!pip install matplotlib
!pip install wordcloud

Requirement already satisfied: matplotlib in c:\pythontemp\lib\site-packages (3.3.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\pythontemp\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: numpy>=1.15 in c:\pythontemp\lib\site-packages (from matplotlib) (1.20.1)
Requirement already satisfied: cycler>=0.10 in c:\pythontemp\lib\site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\pythontemp\lib\site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in c:\pythontemp\lib\site-packages (from matplotlib) (8.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\pythontemp\lib\site-packages (from matplotlib) (2.8.1)
Requirement already satisfied: six in c:\pythontemp\lib\site-packages (from cycler>=0.10->matplotlib) (1.15.0)
Requirement already satisfied: wordcloud in c:\pythontemp\lib\site-packages (1.8.1)
Requirement already satisfied: matplotlib in c:\pythontemp\lib\site-packages (from wordcloud) (3.3.4)
Requirement already satisfied: numpy>=1.6.1 in c:\pythontemp\lib\site-packages (from wordcloud) (1.20.1)
Requirement already satisfied: pillow in c:\pythontemp\lib\site-packages (from wordcloud) (8.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\pythontemp\lib\site-packages (from matplotlib->wordcloud) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\pythontemp\lib\site-packages (from matplotlib->wordcloud) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\pythontemp\lib\site-packages (from matplotlib->wordcloud) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\pythontemp\lib\site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: six in c:\pythontemp\lib\site-packages (from cycler>=0.10->matplotlib->wordcloud) (1.15.0)

In [22]:
import pandas as pd
import numpy as np
import csv
df=pd.read_excel('C:/Users/user/bigdata/accident.xls')
df

,기간,자치구별,구분,합계,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,2020,합계,발생건수,35227,2788,2999,2561,2724,3139,3189,3162,2926,2991,3122,3007,2619
1,2020,합계,사망자수,219,18,20,21,17,18,15,15,19,21,20,19,16
2,2020,합계,부상자수,47513,3944,3980,3385,3724,4294,4372,4319,3948,4035,4143,3926,3443
3,2020,종로구,발생건수,903,76,90,55,61,83,82,89,69,73,75,82,68
4,2020,종로구,사망자수,5,1,1,-,-,1,-,-,1,-,-,1,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2020,송파구,사망자수,11,1,1,1,3,-,-,1,-,2,2,-,-
74,2020,송파구,부상자수,3509,354,245,235,276,294,321,317,259,300,312,331,265
75,2020,강동구,발생건수,1268,100,102,66,117,119,118,100,100,122,109,103,112
76,2020,강동구,사망자수,7,-,1,-,1,-,-,-,1,2,1,-,1
77,2020,강동구,부상자수,1600,122,130,82,151,150,150,122,123,173,137,126,134

In [25]:
df3=pd.read_excel('C:/Users/user/bigdata/accident.xls',)

,기간,자치구별,구분,합계,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월
0,2020,합계,발생건수,35227,2788,2999,2561,2724,3139,3189,3162,2926,2991,3122,3007,2619
1,2020,합계,사망자수,219,18,20,21,17,18,15,15,19,21,20,19,16
2,2020,합계,부상자수,47513,3944,3980,3385,3724,4294,4372,4319,3948,4035,4143,3926,3443
3,2020,종로구,발생건수,903,76,90,55,61,83,82,89,69,73,75,82,68
4,2020,종로구,사망자수,5,1,1,-,-,1,-,-,1,-,-,1,-