In [2]:
import pandas as pd
jejudata19=pd.read_excel('data19.xlsx')
del jejudata19["데이터기준일자"]
del jejudata19["총 유동인구"]
pd.options.display.float_format = '{:.2f}'.format
jejudata19

              년월   시도명 읍면동명                      업종명   이용자수       이용금액
0     2019-01-01  서귀포시  남원읍               건강보조식품 소매업      8     472000
1     2019-01-01  서귀포시  남원읍                  골프장 운영업   3667  608346185
2     2019-01-01  서귀포시  남원읍              과실 및 채소 소매업   1525  135385807
3     2019-01-01  서귀포시  남원읍        관광 민예품 및 선물용품 소매업    241    4915500
4     2019-01-01  서귀포시  남원읍             그외 기타 종합 소매업     15   11905000
...          ...   ...  ...                      ...    ...        ...
14210 2019-12-01   제주시  화북동              차량용 주유소 운영업  10959  700951208
14211 2019-12-01   제주시  화북동                  체인화 편의점  18150  158835020
14212 2019-12-01   제주시  화북동  피자, 햄버거, 샌드위치 및 유사 음식점업   2436   48855810
14213 2019-12-01   제주시  화북동                  한식 음식점업  17626  670361636
14214 2019-12-01   제주시  화북동            화장품 및 방향제 소매업    262   19415860

[14215 rows x 6 columns]

In [3]:
total=jejudata19.groupby(["읍면동명"],as_index=False).sum()


total = total.sort_values(by=['읍면동명'] ,ascending=True)
del total["이용자수"]
del total["이용금액"]
total.to_csv("행정동명.csv",index=True)

In [4]:
import matplotlib.pyplot as plt
import os
if os.name == 'posix':

    plt.rc("font", family="AppleGothic")

else:

    plt.rc("font", family="Malgun Gothic")
plt.figure()

plt.show()

In [5]:
#계절별

food=jejudata19[(jejudata19["업종명"]=="한식 음식점업")
    |(jejudata19["업종명"]=="중식 음식점업")
    |(jejudata19["업종명"]=="일식 음식점업")
    |(jejudata19["업종명"]=="서양식 음식점업")
    |(jejudata19["업종명"]=="비알콜 음료점업")
    |(jejudata19["업종명"]=="기타 외국식 음식점")
    |(jejudata19["업종명"]=="피자, 햄버거, 샌드위치 및 유사 음식점업")]

food_spring=food[(food["년월"]=="2019-03-01")
                |(food["년월"]=="2019-04-01")
                |(food["년월"]=="2019-05-01")]

food_summer=food[(food["년월"]=="2019-06-01")
                |(food["년월"]=="2019-07-01")
                |(food["년월"]=="2019-08-01")]
food_fall=food[(food["년월"]=="2019-09-01")
                |(food["년월"]=="2019-10-01")
                |(food["년월"]=="2019-11-01")]

food_winter=food[(food["년월"]=="2019-12-01")
                |(food["년월"]=="2019-01-01")
                |(food["년월"]=="2019-02-01")]



food_spring=food_spring.groupby(["읍면동명"],as_index=False).sum()
food_spring["1인당 이용금액"] = food_spring["이용금액"]/food_spring["이용자수"]
food_spring["계절"]="봄"
food_spring = food_spring.sort_values(by=["1인당 이용금액"],ascending=[False])


food_summer=food_summer.groupby(["읍면동명"],as_index=False).sum()
food_summer["1인당 이용금액"] = food_summer["이용금액"]/food_summer["이용자수"]
food_summer["계절"]="여름"
food_summer = food_summer.sort_values(by=["1인당 이용금액"],ascending=[False])


food_fall=food_fall.groupby(["읍면동명"],as_index=False).sum()
food_fall["1인당 이용금액"] = food_fall["이용금액"]/food_fall["이용자수"]
food_fall["계절"]="가을"
food_fall = food_fall.sort_values(by=["1인당 이용금액"],ascending=[False])


food_winter=food_winter.groupby(["읍면동명"],as_index=False).sum()
food_winter["1인당 이용금액"] = food_winter["이용금액"]/food_winter["이용자수"]
food_winter["계절"]="겨울"
food_winter = food_winter.sort_values(by=["1인당 이용금액"],ascending=[False])

food=pd.concat([food_spring,food_summer,food_fall,food_winter])
food_1=food[food['읍면동명']=="송산동"]
food_1

   읍면동명    이용자수         이용금액  1인당 이용금액  계절
15  송산동  282680  11517387193  40743.55   봄
15  송산동  316300  12087928083  38216.66  여름
15  송산동  285830  11175288682  39097.68  가을
15  송산동  281643  11661888417  41406.63  겨울

In [10]:
sleep=jejudata19[(jejudata19["업종명"]=="호텔업")
                |(jejudata19["업종명"]=="휴양콘도")
                |(jejudata19["업종명"]=="여관업")]


sleep_spring=sleep[(sleep["년월"]=="2019-03-01")
                |(sleep["년월"]=="2019-04-01")
                |(sleep["년월"]=="2019-05-01")]

sleep_summer=sleep[(sleep["년월"]=="2019-06-01")
                |(sleep["년월"]=="2019-07-01")
                |(sleep["년월"]=="2019-08-01")]

sleep_fall=sleep[(sleep["년월"]=="2019-09-01")
                |(sleep["년월"]=="2019-10-01")
                |(sleep["년월"]=="2019-11-01")]

sleep_winter=sleep[(sleep["년월"]=="2019-12-01")
                |(sleep["년월"]=="2019-01-01")
                |(sleep["년월"]=="2019-02-01")]

sleep_spring=sleep_spring.groupby(["읍면동명"],as_index=False).sum()
sleep_spring["1인당 이용금액"] = sleep_spring["이용금액"]/sleep_spring["이용자수"]
sleep_spring["계절"]="봄"
sleep_spring = sleep_spring.sort_values(by=["1인당 이용금액"],ascending=[False])


sleep_summer=sleep_summer.groupby(["읍면동명"],as_index=False).sum()
sleep_summer["1인당 이용금액"] = sleep_summer["이용금액"]/sleep_summer["이용자수"]
sleep_summer["계절"]="여름"
sleep_summer = sleep_summer.sort_values(by=["1인당 이용금액"],ascending=[False])


sleep_fall=sleep_fall.groupby(["읍면동명"],as_index=False).sum()
sleep_fall["1인당 이용금액"] = sleep_fall["이용금액"]/sleep_fall["이용자수"]
sleep_fall["계절"]="가을"
sleep_fall = sleep_fall.sort_values(by=["1인당 이용금액"],ascending=[False])


sleep_winter=sleep_winter.groupby(["읍면동명"],as_index=False).sum()
sleep_winter["1인당 이용금액"] = sleep_winter["이용금액"]/sleep_winter["이용자수"]
sleep_winter["계절"]="겨울"
sleep_winter = sleep_winter.sort_values(by=["1인당 이용금액"],ascending=[False])

sleep1=pd.concat([sleep_spring,sleep_summer,sleep_fall,sleep_winter])
sleep_1=sleep[sleep['읍면동명']=="예래동"]
sleep_1.to_csv("계절별-숙박.csv")

In [11]:
activity=jejudata19[(jejudata19["업종명"]=="스포츠 및 레크레이션 용품 임대업")
                    |(jejudata19["업종명"]=="기타 수상오락 서비스업")]

sleep_spring=activity[(activity["년월"]=="2019-03-01")
                |(activity["년월"]=="2019-04-01")
                |(activity["년월"]=="2019-05-01")]

sleep_summer=activity[(activity["년월"]=="2019-06-01")
                |(activity["년월"]=="2019-07-01")
                |(activity["년월"]=="2019-08-01")]

sleep_fall=activity[(activity["년월"]=="2019-09-01")
                |(activity["년월"]=="2019-10-01")
                |(activity["년월"]=="2019-11-01")]

sleep_winter=activity[(activity["년월"]=="2019-12-01")
                |(activity["년월"]=="2019-01-01")
                |(activity["년월"]=="2019-02-01")]

sleep_spring=sleep_spring.groupby(["읍면동명"],as_index=False).sum()
sleep_spring["1인당 이용금액"] = sleep_spring["이용금액"]/sleep_spring["이용자수"]
sleep_spring["계절"]="봄"
sleep_spring = sleep_spring.sort_values(by=["1인당 이용금액"],ascending=[False])

sleep_summer=sleep_summer.groupby(["읍면동명"],as_index=False).sum()
sleep_summer["1인당 이용금액"] = sleep_summer["이용금액"]/sleep_summer["이용자수"]
sleep_summer["계절"]="여름"
sleep_summer = sleep_summer.sort_values(by=["1인당 이용금액"],ascending=[False])


sleep_fall=sleep_fall.groupby(["읍면동명"],as_index=False).sum()
sleep_fall["1인당 이용금액"] = sleep_fall["이용금액"]/sleep_fall["이용자수"]
sleep_fall["계절"]="가을"
sleep_fall = sleep_fall.sort_values(by=["1인당 이용금액"],ascending=[False])


sleep_winter=sleep_winter.groupby(["읍면동명"],as_index=False).sum()
sleep_winter["1인당 이용금액"] = sleep_winter["이용금액"]/sleep_winter["이용자수"]
sleep_winter["계절"]="겨울"
sleep_winter = sleep_winter.sort_values(by=["1인당 이용금액"],ascending=[False])


sleep2=pd.concat([sleep_spring,sleep_summer,sleep_fall,sleep_winter])
sleep_1=sleep[sleep['읍면동명']=="일도1동"]
sleep_1.to_csv("계절별-문화레저.csv")

In [12]:
some=jejudata19[(jejudata19['업종명']=="과실 및 채소 소매업")
    |(jejudata19["업종명"]=="관광 민예품 및 선물용품 소매업")
   |(jejudata19["업종명"]=="수산물 소매업")
    |(jejudata19["업종명"]=="육류 소매업")
    |(jejudata19["업종명"]=="빵 및 과자류 소매업")
    |(jejudata19["업종명"]=="화장품 및 방향제 소매업")]

sleep_spring=some[(some["년월"]=="2019-03-01")
                |(some["년월"]=="2019-04-01")
                |(some["년월"]=="2019-05-01")]

sleep_summer=some[(some["년월"]=="2019-06-01")
                |(some["년월"]=="2019-07-01")
                |(some["년월"]=="2019-08-01")]

sleep_fall=some[(some["년월"]=="2019-09-01")
                |(some["년월"]=="2019-10-01")
                |(some["년월"]=="2019-11-01")]

sleep_winter=some[(some["년월"]=="2019-12-01")
                |(some["년월"]=="2019-01-01")
                |(some["년월"]=="2019-02-01")]

sleep_spring=sleep_spring.groupby(["읍면동명"],as_index=False).sum()
sleep_spring["1인당 이용금액"] = sleep_spring["이용금액"]/sleep_spring["이용자수"]
sleep_spring["계절"]="봄"
sleep_spring = sleep_spring.sort_values(by=["1인당 이용금액"],ascending=[False])

sleep_summer=sleep_summer.groupby(["읍면동명"],as_index=False).sum()
sleep_summer["1인당 이용금액"] = sleep_summer["이용금액"]/sleep_summer["이용자수"]
sleep_summer["계절"]="여름"
sleep_summer = sleep_summer.sort_values(by=["1인당 이용금액"],ascending=[False])


sleep_fall=sleep_fall.groupby(["읍면동명"],as_index=False).sum()
sleep_fall["1인당 이용금액"] = sleep_fall["이용금액"]/sleep_fall["이용자수"]
sleep_fall["계절"]="가을"
sleep_fall = sleep_fall.sort_values(by=["1인당 이용금액"],ascending=[False])

sleep_winter=sleep_winter.groupby(["읍면동명"],as_index=False).sum()
sleep_winter["1인당 이용금액"] = sleep_winter["이용금액"]/sleep_winter["이용자수"]
sleep_winter["계절"]="겨울"
sleep_winter = sleep_winter.sort_values(by=["1인당 이용금액"],ascending=[False])

sleep3=pd.concat([sleep_spring,sleep_summer,sleep_fall,sleep_winter])
sleep_1=sleep[sleep['읍면동명']=="송산동"]
sleep_1

              년월   시도명 읍면동명  업종명  이용자수       이용금액
208   2019-01-01  서귀포시  송산동  여관업  3385  650664714
221   2019-01-01  서귀포시  송산동  호텔업  1094   89843625
1378  2019-02-01  서귀포시  송산동  여관업  2721  455474930
1391  2019-02-01  서귀포시  송산동  호텔업  1091  107702750
2553  2019-03-01  서귀포시  송산동  여관업  2951  364595349
2566  2019-03-01  서귀포시  송산동  호텔업  1086  108206130
3743  2019-04-01  서귀포시  송산동  여관업  2883  437944583
3756  2019-04-01  서귀포시  송산동  호텔업  1197  151348170
4925  2019-05-01  서귀포시  송산동  여관업  3129  392335070
4938  2019-05-01  서귀포시  송산동  호텔업  1352  146994980
6119  2019-06-01  서귀포시  송산동  여관업  3223  456296467
6132  2019-06-01  서귀포시  송산동  호텔업  1275  191794065
7308  2019-07-01  서귀포시  송산동  여관업  3519  395039028
7320  2019-07-01  서귀포시  송산동  호텔업  1289  156998575
8487  2019-08-01  서귀포시  송산동  여관업  4177  401260881
8500  2019-08-01  서귀포시  송산동  호텔업  1645  177272887
9672  2019-09-01  서귀포시  송산동  여관업  3122  302799303
9685  2019-09-01  서귀포시  송산동  호텔업  1239  142007356
10861 2019-10-01  서귀포시  송산동  여관업  3519  429582334
10874 2019-10-01  서귀포시  송산동  호텔업  1279  182899651
12056 2019-11-01  서귀포시  송산동  여관업  3237  417278225
12069 2019-11-01  서귀포시  송산동  호텔업  1335  180989880
13237 2019-12-01  서귀포시  송산동  여관업  3203  411830043
13249 2019-12-01  서귀포시  송산동  호텔업  1455  198805653

In [14]:
total=pd.concat([sleep1,sleep2,sleep3,food])
total.to_csv("계절별데이터.csv")

In [51]:
#이용자수 5개  합쳐서 총 합 추가하고 하나씩 나눠서 비율 누고 그래프
total_people=pd.concat([activity_group,food_group,sleep_group,some_group,shop_group])

total_people=total_people.sort_values(by="읍면동명")

total_people

   읍면동명    이용자수         이용금액   업종명
0   건입동    9161    542308361  문화레저
0   건입동   21782   1567507479    쇼핑
0   건입동  265969  10241713311   숙박업
0   건입동   19244   3021186198   숙박업
0   건입동   43016   3257280423   소매업
..  ...     ...          ...   ...
38  화북동    3455    276811320    쇼핑
42  효돈동   84083   2681782488   숙박업
42  효돈동       1      9800000  문화레저
42  효돈동     150     31457660   숙박업
42  효돈동   20406    791512463   소매업

[211 rows x 4 columns]

In [68]:
data19=pd.concat([activity_group,food_group,sleep_group,some_group,shop_group])
data19=data19.sort_values(by="읍면동명")
data19.to_csv("totalpeople19.csv",index=True)