In [17]:
import pandas as pd
legal=pd.read_csv('C:/Users/user/.jupyter/법정동명.csv')
del legal['Unnamed: 0']
legal = legal.set_index('읍면동명',drop=True)
legal

Empty DataFrame
Columns: []
Index: [강정동, 건입동, 구좌읍, 남원읍, 내도동, 노형동, 대정읍, 대포동, 도남동, 도두이동, 도두일동, 도련이동, 도련일동, 도순동, 도평동, 동홍동, 법환동, 보목동, 봉개동, 삼도이동, 삼도일동, 삼양삼동, 삼양이동, 삼양일동, 상예동, 상효동, 색달동, 서귀동, 서호동, 서홍동, 성산읍, 신효동, 아라이동, 아라일동, 안덕면, 애월읍, 연동, 영남동, 영평동, 오등동, 오라삼동, 오라이동, 오라일동, 외도이동, 외도일동, 용강동, 용담삼동, 용담이동, 용담일동, 우도면, 월평동, 이도이동, 이도일동, 이호이동, 이호일동, 일도이동, 일도일동, 조천읍, 중문동, 추자면, 토평동, 표선면, 하예동, 하원동, 하효동, 한경면, 한림읍, 해안동, 호근동, 화북이동, 화북일동, 회수동, 회천동]

[73 rows x 0 columns]

In [40]:
#제주시
legal
legal.loc[["이도이동","도남동"],"읍면동명"]="이도2동"
legal.loc[["일도일동"],"읍면동명"]="일도1동"
legal.loc[["일도이동"],"읍면동명"]="일도2동"
legal.loc[["이도일동"],"읍면동명"]="이도1동"
legal.loc[["삼도일동"],"읍면동명"]="삼도1동"
legal.loc[["삼도이동"],"읍면동명"]="삼도2동"
legal.loc[["용담일동"],"읍면동명"]="용담1동"
legal.loc[["용담이동","용담삼동"],"읍면동명"]="용담2동"
legal.loc[["화북일동","화북이동"],"읍면동명"]="화북동"
legal.loc[["삼양일동","삼양이동","삼양삼동","도련일동","도련이동"],"읍면동명"]="삼양동"
legal.loc[["봉개동","용강동","회천동"],"읍면동명"]="봉개동"
legal.loc[["아라일동","아라이동","오등동","월평동","영평동"],"읍면동명"]="아라동"
legal.loc[["해안동"],"읍면동명"]="노형동"
legal.loc[["외도일동","외도이동","도평동","내도동"],"읍면동명"]="외도동"
legal.loc[["이호일동","이호이동"],"읍면동명"]="이호동"
legal.loc[["도두일동","도두이동"],"읍면동명"]="도두동"
#서귀포시

#legal.loc["서귀동", '이용금액'] = 

#sg=legal.loc["서귀동"]

#서귀동 4 동홍동 2 토평동2 서홍동2

In [41]:

legal.reset_index(drop=True)
legal.iloc[:,[1]]
legal

     읍면동명  도남동 용담삼동 화북이동 이호이동 도두이동
읍면동명
강정동   NaN  NaN  NaN  NaN  NaN  NaN
건입동   NaN  NaN  NaN  NaN  NaN  NaN
구좌읍   NaN  NaN  NaN  NaN  NaN  NaN
남원읍   NaN  NaN  NaN  NaN  NaN  NaN
내도동   외도동  외도동  외도동  외도동  NaN  NaN
...   ...  ...  ...  ...  ...  ...
호근동   NaN  NaN  NaN  NaN  NaN  NaN
화북이동  화북동  화북동  화북동  화북동  화북동  화북동
화북일동  화북동  화북동  화북동  화북동  화북동  화북동
회수동   NaN  NaN  NaN  NaN  NaN  NaN
회천동   봉개동  봉개동  봉개동  봉개동  NaN  NaN

[73 rows x 6 columns]